# these are the numbers of buttons, axis, and hats on the logitech joystick that I am using
# axis: [0, 1, 2, 3]
# buttons: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
# hat: [0]

# controller mappings below
Button_Mappings:
    Activate_Stepper_Group_1: 6
    Activate_Stepper_Group_2: 7
    Activate_Stepper_Group_3: 8
    Reset_Positioning: 11
# -START-
# -ASG1-
# -ASG2-
# -ASG3-
# -RS1-

Axis_Mappings:
    JoyX: 0
    JoyY: 1
    JoyZ: 2
    JoyS: 3
# -AMX-
# -AMY-
# -AMZ-
# -AMS-

Inverted_Controls:
    X_Flip: False
    Y_Flip: False
    Z_Flip: False
    S_Flip: False
# -ICV1-
# -ICV2-
# -ICV3-
# -ICV4-

DeadZones:
    X_Deadzone: 0.2
    Y_Deadzone: 0.2
    Z_Deadzone: 0.2
    S_Deadzone: 0.2
# -DZX-
# -DZY-
# -DZZ-
# -DZS-

Autonomous_Controls:
    Record: 2
    Stop_Recording: 3
    Playback: 4
    Save: 5
    A1: (-1, 0)
    A2: (1, 0)
    A3: (0, -1)
    A4: (0, 1)
# -AUR-
# -AUSR-
# -AUP-
# -AUS-
# -AU1-
# -AU2-
# -AU3-
# -AU4-

Camera_Config:
    size: (720, 480)
    fps: 30
    numofcams: 2
# -CSWH-
# -CFPS-
# -C#C-